# creates a new npm release
name: test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
      - name: test action
        id: forge
        uses: ./
        with:
          base-report-path: before.json
          report-path: after.json